spring:

  #thymelaef??
  thymeleaf:
    #????
    cache: false

  #?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: abc123
    hikari:
      #????
      pool-name: DateHikariCP
      #??????
      minimum-idle: 5
      #??????????
      idle-timeout: 180000
      #?????
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #????????
      max-lifetime: 180000
      #??????30000(30?)
      connection-timeout: 30000
      #??????????????????
      connection-test-query: SELECT 1

  #redis配置
  redis:
    #服务器地址
    host: 192.168.230.100
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5

  #mybatis-plus??
  mybatis-plus:
    #??Mapper.xml????
    mapper-locations: classpath*:/mapper/*Mapper.xml
    #mybatis-plus????????????
    type-aliases-package: com.example.seckill_shop.pojo

  #rabbitmq
  rabbitmq:
    #服务器地址
    host: 192.168.230.100
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一条消息
        prefetch: 1
        #启动是默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #最大重试间隔时间
        max-interval: 10000ms
        #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
        multiplier: 1


#MyBatis SQL???????????????Mapper.xml????
logging:
  level:
    com.example.seckill_shop.mapper: debug